# name of conda environment
name: alignparse-environment

# channels to install conda dependencies
channels:
  - conda-forge
  - bioconda

# conda dependencies
dependencies:
  - python>=3.7
  - minimap2>=2.17
  - pip
  # install the current package with `pip install.`
  - pip:
    - .
    - dms_variants>=0.8.6
